### ISSUE TITLE
Attachment path incorrect

### ISSUE THREAD

**Issue by btaskew** [maful/github-actions-mailgun#3]
Not sure if this is an issue or just an error on my behalf but hoping for some assistance either way.

Am trying to add an attachment to an email but the action seems to be unable to parse the path correctly.
File is stored in project root, which will therefore be located on the default action worker location at `/home/work/test-project/build.exe`

Have tried the following values but all seem to error:

- `attachment: build.exe` or `attachment: ./build.exe` - Results in action looking for attachment in `/home/runner/work/_actions/maful/github-actions-mailgun/v1.0.1/build.exe`
- `attachment: /home/work/test-project/build.exe` - Results in action looking for attachment in `/home/runner/work/_actions/maful/github-actions-mailgun/v1.0.1/home/work/test-project/build.exe`

Are you able to provide any guidance as to what the correct path should be?

**Comment by maful** [comment]
Thanks for your report @btaskew 

I have been releasing a new version of this action and it contains fixing a bug for the attachment path and completing the documentation. Feel free to use the latest version.

You can check the example here https://github.com/maful/testing-mailgun
